# pull或push仓库，类似git@gitlab.local.com:root/cicd-demo-0331.git时
# 需要gitlab仓库配置ssh keys ， 同时配置下面id_rsa、known_hosts等信息
kind: Secret
apiVersion: v1
metadata:
  name: my-ssh-credentials
data:
  id_rsa: # ... base64-encoded private key ...
  known_hosts: # ... base64-encoded known_hosts file ...
  config: # ... base64-encoded ssh config file ...