# 基于https的git项目，在git clone、push时需要username\password，参考以下配置
# 注意.git-credentials中，链接https://<user>:<pass>@<hostname>， user\pass\hostname含/或:等字符时需要url转义
kind: Secret
apiVersion: v1
metadata:
  name: git-basic-auth-secret
type: Opaque
stringData:
  .gitconfig: |
    [user]
        email = chenhq76@xxx.cn
        name = chenhq76
    [push]
        default = simple
    [http]
        sslVerify = false
    [credential "https://192.168.208.136:10433"]
        helper = store
  .git-credentials: |
    https://root:1%2fIAzRc%2fJT5t%2bncqATItHiRMiGqAtj0Py8y09rcE1tg%3d@192.168.208.136%3a10433