apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-cli
spec:
  params:
  # - name: GOOS
  #   type: string
  #   default: "linux"
  #   description: "for GOOS in darwin linux windows"
  # - name: GOARCH
  #   type: string
  #   default: "amd64"
  #   description: "for GOARCH in 386 amd64"
  # - name: GOFLAGS
  #   type: string
  #   default: "-buildvcs=false"  # 不能省略，否则访问git-clone的目录，会报错
  - name: context-path
    type: string
    default: "."
    description: "main方法所在目录"
  - name: go-build-script
    type: string
    description: The go build script to run.
    default: |
      go version
  workspaces:
  - name: source
    description: The folder where go build work on
  steps:
  - name: go-build
    image: golang:1.19
  #  workingDir: $(workspaces.source.path)
    securityContext:
      runAsUser: 0
    env:
    # - name: GOOS
    #   value: $(params.GOOS)
    # - name: GOARCH
    #   value: $(params.GOARCH)
    # - name: GOFLAGS
    #   value: $(params.GOARCH)
    script: |
      #!/usr/bin/env sh
      set -eu
      go env -w GOFLAGS=-buildvcs=false
      cd $(workspaces.source.path)
      eval '$(params.go-build-script)'
      