apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: go-test-pipeline-run-
spec:
  pipelineRef:
    name: go-test-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
    - name: ssh-directory
      secret:
        secretName: git-credentials
    - name: git-basic-auth-directory
      secret:
        secretName: git-basic-auth-secret
  params:
    - name: repo-url
      value: https://192.168.208.136:10433/root/cicd-demo-go-0410.git
    - name: image-reference
      value: 192.168.208.136/umr/my-golang-app:20230417004
    - name: sync-image-repo-url
      value: https://192.168.208.136:10433/root/fleet-examples.git
    - name: GIT_USER_NAME
      value: chenhq76
    - name: GIT_USER_EMAIL
      value: chenhq76@chinaunicom.cn
    - name: go-build-script
      value: |
        go build -v -o my_go_app
    - name: GIT_SCRIPT
      value: |
        rm -rf ./fleet-examples
        export GIT_SSL_NO_VERIFY=true
        git config --global http.sslVerify "false"
        git clone $(params.sync-image-repo-url)

        cat > update-image.sh << EOF
        #!/bin/sh
        echo "Update image tag ..."
        newImage=\$1
        image=my-golang-app:

        for line in \$(cat ./fleet-examples/simple/golang-sample.yaml)
        do
        case \$line in
          *\$image*) sed -i "s|\$line|\$newImage|g" ./fleet-examples/simple/golang-sample.yaml && echo "updated to \$newImage ...";;
        esac
        done
        EOF
        cat update-image.sh
        chmod +x update-image.sh
        ./update-image.sh  $(params.image-reference)
        cat ./fleet-examples/simple/golang-sample.yaml | grep image
        cd ./fleet-examples
        git add .
        git commit -m "update image to $(params.image-reference)"
        git push origin main